function possibleMoves = findpossibleMoves(playerIIfrom,playerJJfrom,board,player)

% all possible conditions
possibleMoves = [playerIIfrom-1 playerJJfrom;...
                 playerIIfrom+1 playerJJfrom;...
                 playerIIfrom playerJJfrom+1;...
                 playerIIfrom playerJJfrom-1;...
                 playerIIfrom playerJJfrom];

% remove them if they exit the border
possibleMoves(possibleMoves(:,1)==0 | ...
              possibleMoves(:,1)==11 | ...
              possibleMoves(:,2)==0 | ...
              possibleMoves(:,2)==11,:) = [];

% remove them if the ground is too high
possibleMoves( diag(board.g(possibleMoves(:,1),possibleMoves(:,2))) -  board.g(playerIIfrom,playerJJfrom) > 1, :) = [];

% remove if lava or other players
possibleMoves( diag(board.e(possibleMoves(:,1),possibleMoves(:,2))) ~= 0 & ...
               diag(board.e(possibleMoves(:,1),possibleMoves(:,2))) ~= player ,: ) = []; 